# application.yaml
# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /prs

# Tomcat specifics
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  basedir:
  backgroundProcessorDelay: 30 # secs

#日志级别配置
logging:
 path: E:\\log
 level:
  root: info
  org:
   springframework:
    web: debug
  

spring:
  #数据库连接池配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/prs
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #thymleaf配置
  thymeleaf:
    prefix: classpath:/templates/  
    suffix: .html  
    mode: HTML5  
    encoding: UTF-8 